# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseFamilyMember(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FamilyMember']] = 'FamilyMember'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FamilyMemberActions[_PrismaModelT]':
        from .client import get_client

        return actions.FamilyMemberActions[_PrismaModelT](client or get_client(), cls)


class BaseFamilyLink(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FamilyLink']] = 'FamilyLink'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FamilyLinkActions[_PrismaModelT]':
        from .client import get_client

        return actions.FamilyLinkActions[_PrismaModelT](client or get_client(), cls)


class BaseMedicalRecord(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MedicalRecord']] = 'MedicalRecord'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MedicalRecordActions[_PrismaModelT]':
        from .client import get_client

        return actions.MedicalRecordActions[_PrismaModelT](client or get_client(), cls)


class BaseSymptom(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Symptom']] = 'Symptom'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SymptomActions[_PrismaModelT]':
        from .client import get_client

        return actions.SymptomActions[_PrismaModelT](client or get_client(), cls)


class BaseMedicalAsset(_PrismaModel):
    __prisma_model__: ClassVar[Literal['MedicalAsset']] = 'MedicalAsset'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MedicalAssetActions[_PrismaModelT]':
        from .client import get_client

        return actions.MedicalAssetActions[_PrismaModelT](client or get_client(), cls)


class BasePermission(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Permission']] = 'Permission'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PermissionActions[_PrismaModelT]':
        from .client import get_client

        return actions.PermissionActions[_PrismaModelT](client or get_client(), cls)


class BaseRiskFactor(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RiskFactor']] = 'RiskFactor'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RiskFactorActions[_PrismaModelT]':
        from .client import get_client

        return actions.RiskFactorActions[_PrismaModelT](client or get_client(), cls)


class BaseEnvironmentalFactor(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EnvironmentalFactor']] = 'EnvironmentalFactor'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EnvironmentalFactorActions[_PrismaModelT]':
        from .client import get_client

        return actions.EnvironmentalFactorActions[_PrismaModelT](client or get_client(), cls)


