# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('D:/medical/backend/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'windows': 'C:\\Users\\asriv\\.cache\\prisma-python\\binaries\\5.17.0\\393aa359c9ad4a4bb28630fb5613f9c281cde053\\node_modules\\prisma\\query-engine-windows.exe'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    familymember: 'actions.FamilyMemberActions[models.FamilyMember]'
    familylink: 'actions.FamilyLinkActions[models.FamilyLink]'
    medicalrecord: 'actions.MedicalRecordActions[models.MedicalRecord]'
    symptom: 'actions.SymptomActions[models.Symptom]'
    medicalasset: 'actions.MedicalAssetActions[models.MedicalAsset]'
    permission: 'actions.PermissionActions[models.Permission]'
    riskfactor: 'actions.RiskFactorActions[models.RiskFactor]'
    environmentalfactor: 'actions.EnvironmentalFactorActions[models.EnvironmentalFactor]'

    __slots__ = (
        'user',
        'familymember',
        'familylink',
        'medicalrecord',
        'symptom',
        'medicalasset',
        'permission',
        'riskfactor',
        'environmentalfactor',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.familymember = actions.FamilyMemberActions[models.FamilyMember](self, models.FamilyMember)
        self.familylink = actions.FamilyLinkActions[models.FamilyLink](self, models.FamilyLink)
        self.medicalrecord = actions.MedicalRecordActions[models.MedicalRecord](self, models.MedicalRecord)
        self.symptom = actions.SymptomActions[models.Symptom](self, models.Symptom)
        self.medicalasset = actions.MedicalAssetActions[models.MedicalAsset](self, models.MedicalAsset)
        self.permission = actions.PermissionActions[models.Permission](self, models.Permission)
        self.riskfactor = actions.RiskFactorActions[models.RiskFactor](self, models.RiskFactor)
        self.environmentalfactor = actions.EnvironmentalFactorActions[models.EnvironmentalFactor](self, models.EnvironmentalFactor)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': 'D:/medical/backend/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    familymember: 'FamilyMemberBatchActions'
    familylink: 'FamilyLinkBatchActions'
    medicalrecord: 'MedicalRecordBatchActions'
    symptom: 'SymptomBatchActions'
    medicalasset: 'MedicalAssetBatchActions'
    permission: 'PermissionBatchActions'
    riskfactor: 'RiskFactorBatchActions'
    environmentalfactor: 'EnvironmentalFactorBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.familymember = FamilyMemberBatchActions(self)
        self.familylink = FamilyLinkBatchActions(self)
        self.medicalrecord = MedicalRecordBatchActions(self)
        self.symptom = SymptomBatchActions(self)
        self.medicalasset = MedicalAssetBatchActions(self)
        self.permission = PermissionBatchActions(self)
        self.riskfactor = RiskFactorBatchActions(self)
        self.environmentalfactor = EnvironmentalFactorBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class FamilyMemberBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.FamilyMemberCreateInput,
        include: Optional[types.FamilyMemberInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.FamilyMember,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.FamilyMemberCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.FamilyMember,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.FamilyMemberWhereUniqueInput,
        include: Optional[types.FamilyMemberInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.FamilyMember,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.FamilyMemberUpdateInput,
        where: types.FamilyMemberWhereUniqueInput,
        include: Optional[types.FamilyMemberInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.FamilyMember,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.FamilyMemberWhereUniqueInput,
        data: types.FamilyMemberUpsertInput,
        include: Optional[types.FamilyMemberInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.FamilyMember,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.FamilyMemberUpdateManyMutationInput,
        where: types.FamilyMemberWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.FamilyMember,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.FamilyMemberWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.FamilyMember,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class FamilyLinkBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.FamilyLinkCreateInput,
        include: Optional[types.FamilyLinkInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.FamilyLink,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.FamilyLinkCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.FamilyLink,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.FamilyLinkWhereUniqueInput,
        include: Optional[types.FamilyLinkInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.FamilyLink,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.FamilyLinkUpdateInput,
        where: types.FamilyLinkWhereUniqueInput,
        include: Optional[types.FamilyLinkInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.FamilyLink,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.FamilyLinkWhereUniqueInput,
        data: types.FamilyLinkUpsertInput,
        include: Optional[types.FamilyLinkInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.FamilyLink,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.FamilyLinkUpdateManyMutationInput,
        where: types.FamilyLinkWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.FamilyLink,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.FamilyLinkWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.FamilyLink,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MedicalRecordBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MedicalRecordCreateInput,
        include: Optional[types.MedicalRecordInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.MedicalRecord,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MedicalRecordCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.MedicalRecord,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MedicalRecordWhereUniqueInput,
        include: Optional[types.MedicalRecordInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.MedicalRecord,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MedicalRecordUpdateInput,
        where: types.MedicalRecordWhereUniqueInput,
        include: Optional[types.MedicalRecordInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.MedicalRecord,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MedicalRecordWhereUniqueInput,
        data: types.MedicalRecordUpsertInput,
        include: Optional[types.MedicalRecordInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.MedicalRecord,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MedicalRecordUpdateManyMutationInput,
        where: types.MedicalRecordWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.MedicalRecord,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MedicalRecordWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.MedicalRecord,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SymptomBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SymptomCreateInput,
        include: Optional[types.SymptomInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Symptom,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SymptomCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Symptom,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SymptomWhereUniqueInput,
        include: Optional[types.SymptomInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Symptom,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SymptomUpdateInput,
        where: types.SymptomWhereUniqueInput,
        include: Optional[types.SymptomInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Symptom,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SymptomWhereUniqueInput,
        data: types.SymptomUpsertInput,
        include: Optional[types.SymptomInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Symptom,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SymptomUpdateManyMutationInput,
        where: types.SymptomWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Symptom,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SymptomWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Symptom,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MedicalAssetBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MedicalAssetCreateInput,
        include: Optional[types.MedicalAssetInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.MedicalAsset,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MedicalAssetCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.MedicalAsset,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MedicalAssetWhereUniqueInput,
        include: Optional[types.MedicalAssetInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.MedicalAsset,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MedicalAssetUpdateInput,
        where: types.MedicalAssetWhereUniqueInput,
        include: Optional[types.MedicalAssetInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.MedicalAsset,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MedicalAssetWhereUniqueInput,
        data: types.MedicalAssetUpsertInput,
        include: Optional[types.MedicalAssetInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.MedicalAsset,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MedicalAssetUpdateManyMutationInput,
        where: types.MedicalAssetWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.MedicalAsset,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MedicalAssetWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.MedicalAsset,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PermissionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PermissionCreateInput,
        include: Optional[types.PermissionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Permission,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PermissionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Permission,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PermissionWhereUniqueInput,
        include: Optional[types.PermissionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Permission,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PermissionUpdateInput,
        where: types.PermissionWhereUniqueInput,
        include: Optional[types.PermissionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Permission,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PermissionWhereUniqueInput,
        data: types.PermissionUpsertInput,
        include: Optional[types.PermissionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Permission,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PermissionUpdateManyMutationInput,
        where: types.PermissionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Permission,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PermissionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Permission,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class RiskFactorBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.RiskFactorCreateInput,
        include: Optional[types.RiskFactorInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.RiskFactor,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.RiskFactorCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.RiskFactor,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.RiskFactorWhereUniqueInput,
        include: Optional[types.RiskFactorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.RiskFactor,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.RiskFactorUpdateInput,
        where: types.RiskFactorWhereUniqueInput,
        include: Optional[types.RiskFactorInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.RiskFactor,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.RiskFactorWhereUniqueInput,
        data: types.RiskFactorUpsertInput,
        include: Optional[types.RiskFactorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.RiskFactor,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.RiskFactorUpdateManyMutationInput,
        where: types.RiskFactorWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.RiskFactor,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.RiskFactorWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.RiskFactor,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class EnvironmentalFactorBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.EnvironmentalFactorCreateInput,
        include: Optional[types.EnvironmentalFactorInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.EnvironmentalFactor,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.EnvironmentalFactorCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.EnvironmentalFactor,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.EnvironmentalFactorWhereUniqueInput,
        include: Optional[types.EnvironmentalFactorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.EnvironmentalFactor,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.EnvironmentalFactorUpdateInput,
        where: types.EnvironmentalFactorWhereUniqueInput,
        include: Optional[types.EnvironmentalFactorInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.EnvironmentalFactor,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.EnvironmentalFactorWhereUniqueInput,
        data: types.EnvironmentalFactorUpsertInput,
        include: Optional[types.EnvironmentalFactorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.EnvironmentalFactor,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.EnvironmentalFactorUpdateManyMutationInput,
        where: types.EnvironmentalFactorWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.EnvironmentalFactor,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.EnvironmentalFactorWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.EnvironmentalFactor,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma