from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'FamilyMember',
    'FamilyLink',
    'MedicalRecord',
    'Symptom',
    'MedicalAsset',
    'Permission',
    'RiskFactor',
    'EnvironmentalFactor',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'permissionsReceived': 'Permission',
        'permissionsGiven': 'Permission',
        'linkedAsMember': 'FamilyMember',
        'createdFamilyMembers': 'FamilyMember',
        'familyLinks': 'FamilyLink',
        'medicalRecords': 'MedicalRecord',
        'createdMedicalRecords': 'MedicalRecord',
        'symptoms': 'Symptom',
        'createdSymptoms': 'Symptom',
        'medicalAssets': 'MedicalAsset',
        'riskFactors': 'RiskFactor',
        'environmentalFactors': 'EnvironmentalFactor',
    },
    'FamilyMember': {
        'createdByUser': 'User',
        'linkedUser': 'User',
        'familyLinks': 'FamilyLink',
        'medicalRecords': 'MedicalRecord',
        'symptoms': 'Symptom',
        'medicalAssets': 'MedicalAsset',
        'riskFactors': 'RiskFactor',
        'environmentalFactors': 'EnvironmentalFactor',
    },
    'FamilyLink': {
        'user': 'User',
        'familyMember': 'FamilyMember',
    },
    'MedicalRecord': {
        'recordedBy': 'User',
        'user': 'User',
        'familyMember': 'FamilyMember',
        'medicalAssets': 'MedicalAsset',
    },
    'Symptom': {
        'addedBy': 'User',
        'user': 'User',
        'familyMember': 'FamilyMember',
    },
    'MedicalAsset': {
        'user': 'User',
        'familyMember': 'FamilyMember',
        'medicalRecord': 'MedicalRecord',
    },
    'Permission': {
        'viewer': 'User',
        'target': 'User',
    },
    'RiskFactor': {
        'user': 'User',
        'familyMember': 'FamilyMember',
    },
    'EnvironmentalFactor': {
        'user': 'User',
        'familyMember': 'FamilyMember',
    },
}

# fmt: on