# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
import os
import logging
import inspect
import warnings
from collections import OrderedDict

from pydantic import BaseModel, Field

from . import types, enums, errors, fields, bases
from ._types import FuncType
from ._compat import model_rebuild, field_validator
from ._builder import serialize_base64
from .generator import partial_models_ctx, PartialModelField


log: logging.Logger = logging.getLogger(__name__)
_created_partial_types: Set[str] = set()

class User(bases.BaseUser):
    """Represents a User record"""

    id: _str
    email: _str
    name: Optional[_str] = None
    password: _str
    role: 'enums.Role'
    gender: Optional[_str] = None
    dateOfBirth: Optional[datetime.datetime] = None
    phoneNumber: Optional[_str] = None
    permissionsReceived: Optional[List['models.Permission']] = None
    permissionsGiven: Optional[List['models.Permission']] = None
    linkedAsMember: Optional[List['models.FamilyMember']] = None
    createdFamilyMembers: Optional[List['models.FamilyMember']] = None
    familyLinks: Optional[List['models.FamilyLink']] = None
    medicalRecords: Optional[List['models.MedicalRecord']] = None
    createdMedicalRecords: Optional[List['models.MedicalRecord']] = None
    symptoms: Optional[List['models.Symptom']] = None
    createdSymptoms: Optional[List['models.Symptom']] = None
    medicalAssets: Optional[List['models.MedicalAsset']] = None
    riskFactors: Optional[List['models.RiskFactor']] = None
    environmentalFactors: Optional[List['models.EnvironmentalFactor']] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.UserKeys']] = None,
        exclude: Optional[Iterable['types.UserKeys']] = None,
        required: Optional[Iterable['types.UserKeys']] = None,
        optional: Optional[Iterable['types.UserKeys']] = None,
        relations: Optional[Mapping['types.UserRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.UserKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _User_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _User_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _User_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _User_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _User_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _User_relational_fields:
                        raise errors.UnknownRelationalFieldError('User', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid User / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'User',
            }
        )
        _created_partial_types.add(name)


class FamilyMember(bases.BaseFamilyMember):
    """Represents a FamilyMember record"""

    id: _str
    fullName: _str
    gender: Optional[_str] = None
    dateOfBirth: Optional[datetime.datetime] = None
    dateOfDeath: Optional[datetime.datetime] = None
    ethnicity: Optional[_str] = None
    relationToCreator: _str
    isManualEntry: _bool
    createdAt: datetime.datetime
    createdByUser: Optional['models.User'] = None
    createdByUserId: _str
    linkedUser: Optional['models.User'] = None
    linkedUserId: Optional[_str] = None
    familyLinks: Optional[List['models.FamilyLink']] = None
    medicalRecords: Optional[List['models.MedicalRecord']] = None
    symptoms: Optional[List['models.Symptom']] = None
    medicalAssets: Optional[List['models.MedicalAsset']] = None
    riskFactors: Optional[List['models.RiskFactor']] = None
    environmentalFactors: Optional[List['models.EnvironmentalFactor']] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.FamilyMemberKeys']] = None,
        exclude: Optional[Iterable['types.FamilyMemberKeys']] = None,
        required: Optional[Iterable['types.FamilyMemberKeys']] = None,
        optional: Optional[Iterable['types.FamilyMemberKeys']] = None,
        relations: Optional[Mapping['types.FamilyMemberRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.FamilyMemberKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _FamilyMember_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _FamilyMember_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _FamilyMember_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _FamilyMember_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _FamilyMember_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _FamilyMember_relational_fields:
                        raise errors.UnknownRelationalFieldError('FamilyMember', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid FamilyMember / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'FamilyMember',
            }
        )
        _created_partial_types.add(name)


class FamilyLink(bases.BaseFamilyLink):
    """Represents a FamilyLink record"""

    id: _str
    user: Optional['models.User'] = None
    userId: _str
    familyMemberId: _str
    relation: _str
    status: _str
    createdAt: datetime.datetime
    familyMember: Optional['models.FamilyMember'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.FamilyLinkKeys']] = None,
        exclude: Optional[Iterable['types.FamilyLinkKeys']] = None,
        required: Optional[Iterable['types.FamilyLinkKeys']] = None,
        optional: Optional[Iterable['types.FamilyLinkKeys']] = None,
        relations: Optional[Mapping['types.FamilyLinkRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.FamilyLinkKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _FamilyLink_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _FamilyLink_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _FamilyLink_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _FamilyLink_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _FamilyLink_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _FamilyLink_relational_fields:
                        raise errors.UnknownRelationalFieldError('FamilyLink', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid FamilyLink / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'FamilyLink',
            }
        )
        _created_partial_types.add(name)


class MedicalRecord(bases.BaseMedicalRecord):
    """Represents a MedicalRecord record"""

    id: _str
    userId: Optional[_str] = None
    familyMemberId: Optional[_str] = None
    recordType: _str
    conditionName: _str
    category: _str
    ageOfOnset: Optional[_int] = None
    severity: Optional[_str] = None
    isGenetic: _bool
    treatmentNotes: Optional[_str] = None
    diagnosedAt: Optional[datetime.datetime] = None
    recordedBy: Optional['models.User'] = None
    recordedById: _str
    createdAt: datetime.datetime
    user: Optional['models.User'] = None
    familyMember: Optional['models.FamilyMember'] = None
    medicalAssets: Optional[List['models.MedicalAsset']] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.MedicalRecordKeys']] = None,
        exclude: Optional[Iterable['types.MedicalRecordKeys']] = None,
        required: Optional[Iterable['types.MedicalRecordKeys']] = None,
        optional: Optional[Iterable['types.MedicalRecordKeys']] = None,
        relations: Optional[Mapping['types.MedicalRecordRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.MedicalRecordKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _MedicalRecord_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _MedicalRecord_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _MedicalRecord_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _MedicalRecord_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _MedicalRecord_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _MedicalRecord_relational_fields:
                        raise errors.UnknownRelationalFieldError('MedicalRecord', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid MedicalRecord / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'MedicalRecord',
            }
        )
        _created_partial_types.add(name)


class Symptom(bases.BaseSymptom):
    """Represents a Symptom record"""

    id: _str
    userId: Optional[_str] = None
    familyMemberId: Optional[_str] = None
    symptom: _str
    severity: Optional[_str] = None
    onsetDate: Optional[datetime.datetime] = None
    durationDays: Optional[_int] = None
    associatedCondition: Optional[_str] = None
    createdAt: datetime.datetime
    addedBy: Optional['models.User'] = None
    addedById: _str
    user: Optional['models.User'] = None
    familyMember: Optional['models.FamilyMember'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.SymptomKeys']] = None,
        exclude: Optional[Iterable['types.SymptomKeys']] = None,
        required: Optional[Iterable['types.SymptomKeys']] = None,
        optional: Optional[Iterable['types.SymptomKeys']] = None,
        relations: Optional[Mapping['types.SymptomRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.SymptomKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _Symptom_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _Symptom_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _Symptom_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _Symptom_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Symptom_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Symptom_relational_fields:
                        raise errors.UnknownRelationalFieldError('Symptom', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Symptom / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'Symptom',
            }
        )
        _created_partial_types.add(name)


class MedicalAsset(bases.BaseMedicalAsset):
    """Represents a MedicalAsset record"""

    id: _str
    userId: _str
    familyMemberId: Optional[_str] = None
    assetType: _str
    fileUrl: _str
    description: Optional[_str] = None
    associatedRecordId: Optional[_str] = None
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    tags: List[_str]
    user: Optional['models.User'] = None
    familyMember: Optional['models.FamilyMember'] = None
    medicalRecord: Optional['models.MedicalRecord'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )

    @field_validator('tags', pre=True, allow_reuse=True)
    @classmethod
    def _transform_required_list_fields(cls, value: object) -> object:
        # When using raw queries, some databases will return `None` for an array field that has not been set yet.
        #
        # In our case we want to use an empty list instead as that is the internal Prisma behaviour and we want
        # to use the same consistent structure between the core ORM and raw queries. For example, if we updated
        # our type definitions to include `None` for `List` fields then it would be misleading as it will only
        # ever be `None` in raw queries.
        if value is None:
            return []

        return value

    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.MedicalAssetKeys']] = None,
        exclude: Optional[Iterable['types.MedicalAssetKeys']] = None,
        required: Optional[Iterable['types.MedicalAssetKeys']] = None,
        optional: Optional[Iterable['types.MedicalAssetKeys']] = None,
        relations: Optional[Mapping['types.MedicalAssetRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.MedicalAssetKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _MedicalAsset_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _MedicalAsset_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _MedicalAsset_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _MedicalAsset_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _MedicalAsset_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _MedicalAsset_relational_fields:
                        raise errors.UnknownRelationalFieldError('MedicalAsset', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid MedicalAsset / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'MedicalAsset',
            }
        )
        _created_partial_types.add(name)


class Permission(bases.BasePermission):
    """Represents a Permission record"""

    id: _str
    viewerUserId: _str
    targetUserId: _str
    accessLevel: _str
    expiresAt: Optional[datetime.datetime] = None
    createdAt: datetime.datetime
    viewer: Optional['models.User'] = None
    target: Optional['models.User'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.PermissionKeys']] = None,
        exclude: Optional[Iterable['types.PermissionKeys']] = None,
        required: Optional[Iterable['types.PermissionKeys']] = None,
        optional: Optional[Iterable['types.PermissionKeys']] = None,
        relations: Optional[Mapping['types.PermissionRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.PermissionKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _Permission_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _Permission_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _Permission_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _Permission_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Permission_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Permission_relational_fields:
                        raise errors.UnknownRelationalFieldError('Permission', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Permission / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'Permission',
            }
        )
        _created_partial_types.add(name)


class RiskFactor(bases.BaseRiskFactor):
    """Represents a RiskFactor record"""

    id: _str
    userId: Optional[_str] = None
    familyMemberId: Optional[_str] = None
    bmi: Optional[_float] = None
    smokingStatus: Optional[_str] = None
    alcoholUse: Optional[_str] = None
    physicalActivity: Optional[_str] = None
    dietType: Optional[_str] = None
    occupationType: Optional[_str] = None
    stressLevel: Optional[_str] = None
    createdAt: datetime.datetime
    user: Optional['models.User'] = None
    familyMember: Optional['models.FamilyMember'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.RiskFactorKeys']] = None,
        exclude: Optional[Iterable['types.RiskFactorKeys']] = None,
        required: Optional[Iterable['types.RiskFactorKeys']] = None,
        optional: Optional[Iterable['types.RiskFactorKeys']] = None,
        relations: Optional[Mapping['types.RiskFactorRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.RiskFactorKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _RiskFactor_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _RiskFactor_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _RiskFactor_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _RiskFactor_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _RiskFactor_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _RiskFactor_relational_fields:
                        raise errors.UnknownRelationalFieldError('RiskFactor', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid RiskFactor / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'RiskFactor',
            }
        )
        _created_partial_types.add(name)


class EnvironmentalFactor(bases.BaseEnvironmentalFactor):
    """Represents a EnvironmentalFactor record"""

    id: _str
    userId: Optional[_str] = None
    familyMemberId: Optional[_str] = None
    location: Optional[_str] = None
    pollutionLevel: Optional[_str] = None
    diseaseOutbreaks: Optional[_str] = None
    createdAt: datetime.datetime
    user: Optional['models.User'] = None
    familyMember: Optional['models.FamilyMember'] = None

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: Optional[bool] = None,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass is not None:
            warnings.warn(
                'The `warn_subclass` argument is deprecated as it is no longer necessary and will be removed in the next release',
                DeprecationWarning,
                stacklevel=3,
            )


    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.EnvironmentalFactorKeys']] = None,
        exclude: Optional[Iterable['types.EnvironmentalFactorKeys']] = None,
        required: Optional[Iterable['types.EnvironmentalFactorKeys']] = None,
        optional: Optional[Iterable['types.EnvironmentalFactorKeys']] = None,
        relations: Optional[Mapping['types.EnvironmentalFactorRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.EnvironmentalFactorKeys', PartialModelField] = OrderedDict()

        try:
            if include:
                for field in include:
                    fields[field] = _EnvironmentalFactor_fields[field].copy()
            elif exclude:
                for field in exclude:
                    if field not in _EnvironmentalFactor_fields:
                        raise KeyError(field)

                fields = {
                    key: data.copy()
                    for key, data in _EnvironmentalFactor_fields.items()
                    if key not in exclude
                }
            else:
                fields = {
                    key: data.copy()
                    for key, data in _EnvironmentalFactor_fields.items()
                }

            if required:
                for field in required:
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _EnvironmentalFactor_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _EnvironmentalFactor_relational_fields:
                        raise errors.UnknownRelationalFieldError('EnvironmentalFactor', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid EnvironmentalFactor / {name} field.'
            ) from None

        models = partial_models_ctx.get()
        models.append(
            {
                'name': name,
                'fields': cast(Mapping[str, PartialModelField], fields),
                'from_model': 'EnvironmentalFactor',
            }
        )
        _created_partial_types.add(name)



_User_relational_fields: Set[str] = {
        'permissionsReceived',
        'permissionsGiven',
        'linkedAsMember',
        'createdFamilyMembers',
        'familyLinks',
        'medicalRecords',
        'createdMedicalRecords',
        'symptoms',
        'createdSymptoms',
        'medicalAssets',
        'riskFactors',
        'environmentalFactors',
    }
_User_fields: Dict['types.UserKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('email', {
            'name': 'email',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('name', {
            'name': 'name',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('password', {
            'name': 'password',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('role', {
            'name': 'role',
            'is_list': False,
            'optional': False,
            'type': 'enums.Role',
            'is_relational': False,
            'documentation': None,
        }),
        ('gender', {
            'name': 'gender',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('dateOfBirth', {
            'name': 'dateOfBirth',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('phoneNumber', {
            'name': 'phoneNumber',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('permissionsReceived', {
            'name': 'permissionsReceived',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Permission\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('permissionsGiven', {
            'name': 'permissionsGiven',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Permission\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('linkedAsMember', {
            'name': 'linkedAsMember',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.FamilyMember\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('createdFamilyMembers', {
            'name': 'createdFamilyMembers',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.FamilyMember\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyLinks', {
            'name': 'familyLinks',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.FamilyLink\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalRecords', {
            'name': 'medicalRecords',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalRecord\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('createdMedicalRecords', {
            'name': 'createdMedicalRecords',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalRecord\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('symptoms', {
            'name': 'symptoms',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Symptom\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('createdSymptoms', {
            'name': 'createdSymptoms',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Symptom\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalAssets', {
            'name': 'medicalAssets',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalAsset\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('riskFactors', {
            'name': 'riskFactors',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.RiskFactor\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('environmentalFactors', {
            'name': 'environmentalFactors',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.EnvironmentalFactor\']',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_FamilyMember_relational_fields: Set[str] = {
        'createdByUser',
        'linkedUser',
        'familyLinks',
        'medicalRecords',
        'symptoms',
        'medicalAssets',
        'riskFactors',
        'environmentalFactors',
    }
_FamilyMember_fields: Dict['types.FamilyMemberKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('fullName', {
            'name': 'fullName',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('gender', {
            'name': 'gender',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('dateOfBirth', {
            'name': 'dateOfBirth',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('dateOfDeath', {
            'name': 'dateOfDeath',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('ethnicity', {
            'name': 'ethnicity',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('relationToCreator', {
            'name': 'relationToCreator',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('isManualEntry', {
            'name': 'isManualEntry',
            'is_list': False,
            'optional': False,
            'type': '_bool',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdByUser', {
            'name': 'createdByUser',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('createdByUserId', {
            'name': 'createdByUserId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('linkedUser', {
            'name': 'linkedUser',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('linkedUserId', {
            'name': 'linkedUserId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyLinks', {
            'name': 'familyLinks',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.FamilyLink\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalRecords', {
            'name': 'medicalRecords',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalRecord\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('symptoms', {
            'name': 'symptoms',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.Symptom\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalAssets', {
            'name': 'medicalAssets',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalAsset\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('riskFactors', {
            'name': 'riskFactors',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.RiskFactor\']',
            'is_relational': True,
            'documentation': None,
        }),
        ('environmentalFactors', {
            'name': 'environmentalFactors',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.EnvironmentalFactor\']',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_FamilyLink_relational_fields: Set[str] = {
        'user',
        'familyMember',
    }
_FamilyLink_fields: Dict['types.FamilyLinkKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('relation', {
            'name': 'relation',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('status', {
            'name': 'status',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_MedicalRecord_relational_fields: Set[str] = {
        'recordedBy',
        'user',
        'familyMember',
        'medicalAssets',
    }
_MedicalRecord_fields: Dict['types.MedicalRecordKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('recordType', {
            'name': 'recordType',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('conditionName', {
            'name': 'conditionName',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('category', {
            'name': 'category',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('ageOfOnset', {
            'name': 'ageOfOnset',
            'is_list': False,
            'optional': True,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('severity', {
            'name': 'severity',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('isGenetic', {
            'name': 'isGenetic',
            'is_list': False,
            'optional': False,
            'type': '_bool',
            'is_relational': False,
            'documentation': None,
        }),
        ('treatmentNotes', {
            'name': 'treatmentNotes',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('diagnosedAt', {
            'name': 'diagnosedAt',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('recordedBy', {
            'name': 'recordedBy',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('recordedById', {
            'name': 'recordedById',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalAssets', {
            'name': 'medicalAssets',
            'is_list': True,
            'optional': True,
            'type': 'List[\'models.MedicalAsset\']',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_Symptom_relational_fields: Set[str] = {
        'addedBy',
        'user',
        'familyMember',
    }
_Symptom_fields: Dict['types.SymptomKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('symptom', {
            'name': 'symptom',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('severity', {
            'name': 'severity',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('onsetDate', {
            'name': 'onsetDate',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('durationDays', {
            'name': 'durationDays',
            'is_list': False,
            'optional': True,
            'type': '_int',
            'is_relational': False,
            'documentation': None,
        }),
        ('associatedCondition', {
            'name': 'associatedCondition',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('addedBy', {
            'name': 'addedBy',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('addedById', {
            'name': 'addedById',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_MedicalAsset_relational_fields: Set[str] = {
        'user',
        'familyMember',
        'medicalRecord',
    }
_MedicalAsset_fields: Dict['types.MedicalAssetKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('assetType', {
            'name': 'assetType',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('fileUrl', {
            'name': 'fileUrl',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('description', {
            'name': 'description',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('associatedRecordId', {
            'name': 'associatedRecordId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('updatedAt', {
            'name': 'updatedAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('tags', {
            'name': 'tags',
            'is_list': True,
            'optional': False,
            'type': 'List[_str]',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
        ('medicalRecord', {
            'name': 'medicalRecord',
            'is_list': False,
            'optional': True,
            'type': 'models.MedicalRecord',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_Permission_relational_fields: Set[str] = {
        'viewer',
        'target',
    }
_Permission_fields: Dict['types.PermissionKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('viewerUserId', {
            'name': 'viewerUserId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('targetUserId', {
            'name': 'targetUserId',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('accessLevel', {
            'name': 'accessLevel',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('expiresAt', {
            'name': 'expiresAt',
            'is_list': False,
            'optional': True,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('viewer', {
            'name': 'viewer',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('target', {
            'name': 'target',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_RiskFactor_relational_fields: Set[str] = {
        'user',
        'familyMember',
    }
_RiskFactor_fields: Dict['types.RiskFactorKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('bmi', {
            'name': 'bmi',
            'is_list': False,
            'optional': True,
            'type': '_float',
            'is_relational': False,
            'documentation': None,
        }),
        ('smokingStatus', {
            'name': 'smokingStatus',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('alcoholUse', {
            'name': 'alcoholUse',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('physicalActivity', {
            'name': 'physicalActivity',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('dietType', {
            'name': 'dietType',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('occupationType', {
            'name': 'occupationType',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('stressLevel', {
            'name': 'stressLevel',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)

_EnvironmentalFactor_relational_fields: Set[str] = {
        'user',
        'familyMember',
    }
_EnvironmentalFactor_fields: Dict['types.EnvironmentalFactorKeys', PartialModelField] = OrderedDict(
    [
        ('id', {
            'name': 'id',
            'is_list': False,
            'optional': False,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('userId', {
            'name': 'userId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('familyMemberId', {
            'name': 'familyMemberId',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('location', {
            'name': 'location',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('pollutionLevel', {
            'name': 'pollutionLevel',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('diseaseOutbreaks', {
            'name': 'diseaseOutbreaks',
            'is_list': False,
            'optional': True,
            'type': '_str',
            'is_relational': False,
            'documentation': None,
        }),
        ('createdAt', {
            'name': 'createdAt',
            'is_list': False,
            'optional': False,
            'type': 'datetime.datetime',
            'is_relational': False,
            'documentation': None,
        }),
        ('user', {
            'name': 'user',
            'is_list': False,
            'optional': True,
            'type': 'models.User',
            'is_relational': True,
            'documentation': None,
        }),
        ('familyMember', {
            'name': 'familyMember',
            'is_list': False,
            'optional': True,
            'type': 'models.FamilyMember',
            'is_relational': True,
            'documentation': None,
        }),
    ],
)



# we have to import ourselves as relation types are namespaced to models
# e.g. models.Post
from . import models, actions

# required to support relationships between models
model_rebuild(User)
model_rebuild(FamilyMember)
model_rebuild(FamilyLink)
model_rebuild(MedicalRecord)
model_rebuild(Symptom)
model_rebuild(MedicalAsset)
model_rebuild(Permission)
model_rebuild(RiskFactor)
model_rebuild(EnvironmentalFactor)
