# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# User types

class UserOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the User create method"""
    id: _int
    name: Optional[_str]
    familyMembers: 'FamilyMemberCreateManyNestedWithoutRelationsInput'
    linkedAsMember: 'FamilyMemberCreateManyNestedWithoutRelationsInput'
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserCreateInput(UserOptionalCreateInput):
    """Required arguments to the User create method"""
    email: _str
    password: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class UserOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the User create method, without relations"""
    id: _int
    name: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserCreateWithoutRelationsInput(UserOptionalCreateWithoutRelationsInput):
    """Required arguments to the User create method, without relations"""
    email: _str
    password: _str

class UserConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'UserCreateWithoutRelationsInput'
    where: 'UserWhereUniqueInput'

class UserCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'


class UserCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['UserCreateWithoutRelationsInput', List['UserCreateWithoutRelationsInput']]
    connect: Union['UserWhereUniqueInput', List['UserWhereUniqueInput']]
    connect_or_create: Union['UserConnectOrCreateWithoutRelationsInput', List['UserConnectOrCreateWithoutRelationsInput']]

_UserWhereUnique_id_Input = TypedDict(
    '_UserWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

_UserWhereUnique_email_Input = TypedDict(
    '_UserWhereUnique_email_Input',
    {
        'email': '_str',
    },
    total=True
)

UserWhereUniqueInput = Union[
    '_UserWhereUnique_id_Input',
    '_UserWhereUnique_email_Input',
]


class UserUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    email: _str
    name: Optional[_str]
    password: _str
    familyMembers: 'FamilyMemberUpdateManyWithoutRelationsInput'
    linkedAsMember: 'FamilyMemberUpdateManyWithoutRelationsInput'
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    email: _str
    name: Optional[_str]
    password: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class UserUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['UserCreateWithoutRelationsInput']
    connect: List['UserWhereUniqueInput']
    connect_or_create: List['UserConnectOrCreateWithoutRelationsInput']
    set: List['UserWhereUniqueInput']
    disconnect: List['UserWhereUniqueInput']
    delete: List['UserWhereUniqueInput']

    # TODO
    # update: List['UserUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['UserUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['UserScalarWhereInput']
    # upsert: List['UserUpserteWithWhereUniqueWithoutRelationsInput']


class UserUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'UserUpdateInput'
    # upsert: 'UserUpsertWithoutRelationsInput'


class UserUpsertInput(TypedDict):
    create: 'UserCreateInput'
    update: 'UserUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_User_id_OrderByInput = TypedDict(
    '_User_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_User_email_OrderByInput = TypedDict(
    '_User_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_User_name_OrderByInput = TypedDict(
    '_User_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_User_password_OrderByInput = TypedDict(
    '_User_password_OrderByInput',
    {
        'password': 'SortOrder',
    },
    total=True
)

_User_createdAt_OrderByInput = TypedDict(
    '_User_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_User_updatedAt_OrderByInput = TypedDict(
    '_User_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

_User_RelevanceInner = TypedDict(
    '_User_RelevanceInner',
    {
        'fields': 'List[UserScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_User_RelevanceOrderByInput = TypedDict(
    '_User_RelevanceOrderByInput',
    {
        '_relevance': '_User_RelevanceInner',
    },
    total=True
)

UserOrderByInput = Union[
    '_User_id_OrderByInput',
    '_User_email_OrderByInput',
    '_User_name_OrderByInput',
    '_User_password_OrderByInput',
    '_User_createdAt_OrderByInput',
    '_User_updatedAt_OrderByInput',
    '_User_RelevanceOrderByInput',
]



# recursive User types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

UserRelationFilter = TypedDict(
    'UserRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class UserListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class UserInclude(TypedDict, total=False):
    """User relational arguments"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromUser']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromUser']


    

class UserIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive1']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive1']


class UserIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive2']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive2']


class UserIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive3']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive3']


class UserIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive4']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromUserRecursive4']


class UserIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class UserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyUserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class FamilyMemberIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive1']
    linkedUser: Union[bool, 'UserArgsFromUserRecursive1']


class FamilyMemberIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive2']
    linkedUser: Union[bool, 'UserArgsFromUserRecursive2']


class FamilyMemberIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive3']
    linkedUser: Union[bool, 'UserArgsFromUserRecursive3']


class FamilyMemberIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive4']
    linkedUser: Union[bool, 'UserArgsFromUserRecursive4']


class FamilyMemberIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class FamilyMemberArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive1'


class FamilyMemberArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive2'


class FamilyMemberArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive3'


class FamilyMemberArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive4'


class FamilyMemberArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyFamilyMemberArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive1'


class FindManyFamilyMemberArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive2'


class FindManyFamilyMemberArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive3'


class FindManyFamilyMemberArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive4'


class FindManyFamilyMemberArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    


FindManyUserArgs = FindManyUserArgsFromUser
FindFirstUserArgs = FindManyUserArgsFromUser


    

class UserWhereInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    familyMembers: 'FamilyMemberListRelationFilter'
    linkedAsMember: 'FamilyMemberListRelationFilter'
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive1', List['UserWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive1']
    OR: List['UserWhereInputRecursive1']
    NOT: List['UserWhereInputRecursive1']


class UserWhereInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    familyMembers: 'FamilyMemberListRelationFilter'
    linkedAsMember: 'FamilyMemberListRelationFilter'
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive2', List['UserWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive2']
    OR: List['UserWhereInputRecursive2']
    NOT: List['UserWhereInputRecursive2']


class UserWhereInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    familyMembers: 'FamilyMemberListRelationFilter'
    linkedAsMember: 'FamilyMemberListRelationFilter'
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive3', List['UserWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive3']
    OR: List['UserWhereInputRecursive3']
    NOT: List['UserWhereInputRecursive3']


class UserWhereInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    familyMembers: 'FamilyMemberListRelationFilter'
    linkedAsMember: 'FamilyMemberListRelationFilter'
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive4', List['UserWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive4']
    OR: List['UserWhereInputRecursive4']
    NOT: List['UserWhereInputRecursive4']


class UserWhereInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    email: Union[_str, 'types.StringFilter']
    name: Union[None, _str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    familyMembers: 'FamilyMemberListRelationFilter'
    linkedAsMember: 'FamilyMemberListRelationFilter'
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']



# aggregate User types


    

class UserScalarWhereWithAggregatesInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive1']
    OR: List['UserScalarWhereWithAggregatesInputRecursive1']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive1']


class UserScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive2']
    OR: List['UserScalarWhereWithAggregatesInputRecursive2']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive2']


class UserScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive3']
    OR: List['UserScalarWhereWithAggregatesInputRecursive3']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive3']


class UserScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive4']
    OR: List['UserScalarWhereWithAggregatesInputRecursive4']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive4']


class UserScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class UserGroupByOutput(TypedDict, total=False):
    id: _int
    email: _str
    name: _str
    password: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    _sum: 'UserSumAggregateOutput'
    _avg: 'UserAvgAggregateOutput'
    _min: 'UserMinAggregateOutput'
    _max: 'UserMaxAggregateOutput'
    _count: 'UserCountAggregateOutput'


class UserAvgAggregateOutput(TypedDict, total=False):
    """User output for aggregating averages"""
    id: float


class UserSumAggregateOutput(TypedDict, total=False):
    """User output for aggregating sums"""
    id: _int


class UserScalarAggregateOutput(TypedDict, total=False):
    """User output including scalar fields"""
    id: _int
    email: _str
    name: _str
    password: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


UserMinAggregateOutput = UserScalarAggregateOutput
UserMaxAggregateOutput = UserScalarAggregateOutput


class UserMaxAggregateInput(TypedDict, total=False):
    """User input for aggregating by max"""
    id: bool
    email: bool
    name: bool
    password: bool
    createdAt: bool
    updatedAt: bool


class UserMinAggregateInput(TypedDict, total=False):
    """User input for aggregating by min"""
    id: bool
    email: bool
    name: bool
    password: bool
    createdAt: bool
    updatedAt: bool


class UserNumberAggregateInput(TypedDict, total=False):
    """User input for aggregating numbers"""
    id: bool


UserAvgAggregateInput = UserNumberAggregateInput
UserSumAggregateInput = UserNumberAggregateInput


UserCountAggregateInput = TypedDict(
    'UserCountAggregateInput',
    {
        'id': bool,
        'email': bool,
        'name': bool,
        'password': bool,
        'createdAt': bool,
        'updatedAt': bool,
        '_all': bool,
    },
    total=False,
)

UserCountAggregateOutput = TypedDict(
    'UserCountAggregateOutput',
    {
        'id': int,
        'email': int,
        'name': int,
        'password': int,
        'createdAt': int,
        'updatedAt': int,
        '_all': int,
    },
    total=False,
)


UserKeys = Literal[
    'id',
    'email',
    'name',
    'password',
    'familyMembers',
    'linkedAsMember',
    'createdAt',
    'updatedAt',
]
UserScalarFieldKeys = Literal[
    'id',
    'email',
    'name',
    'password',
    'createdAt',
    'updatedAt',
]
UserScalarFieldKeysT = TypeVar('UserScalarFieldKeysT', bound=UserScalarFieldKeys)

UserRelationalFieldKeys = Literal[
        'familyMembers',
        'linkedAsMember',
    ]

# FamilyMember types

class FamilyMemberOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the FamilyMember create method"""
    id: _int
    userId: _int
    linkedUserId: Optional[_int]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    user: 'UserCreateNestedWithoutRelationsInput'
    linkedUser: 'UserCreateNestedWithoutRelationsInput'


class FamilyMemberCreateInput(FamilyMemberOptionalCreateInput):
    """Required arguments to the FamilyMember create method"""
    name: _str
    relation: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class FamilyMemberOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the FamilyMember create method, without relations"""
    id: _int
    userId: _int
    linkedUserId: Optional[_int]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class FamilyMemberCreateWithoutRelationsInput(FamilyMemberOptionalCreateWithoutRelationsInput):
    """Required arguments to the FamilyMember create method, without relations"""
    name: _str
    relation: _str

class FamilyMemberConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'FamilyMemberCreateWithoutRelationsInput'
    where: 'FamilyMemberWhereUniqueInput'

class FamilyMemberCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'FamilyMemberCreateWithoutRelationsInput'
    connect: 'FamilyMemberWhereUniqueInput'
    connect_or_create: 'FamilyMemberConnectOrCreateWithoutRelationsInput'


class FamilyMemberCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['FamilyMemberCreateWithoutRelationsInput', List['FamilyMemberCreateWithoutRelationsInput']]
    connect: Union['FamilyMemberWhereUniqueInput', List['FamilyMemberWhereUniqueInput']]
    connect_or_create: Union['FamilyMemberConnectOrCreateWithoutRelationsInput', List['FamilyMemberConnectOrCreateWithoutRelationsInput']]

_FamilyMemberWhereUnique_id_Input = TypedDict(
    '_FamilyMemberWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

_FamilyMemberWhereUnique_linkedUserId_Input = TypedDict(
    '_FamilyMemberWhereUnique_linkedUserId_Input',
    {
        'linkedUserId': '_int',
    },
    total=True
)

FamilyMemberWhereUniqueInput = Union[
    '_FamilyMemberWhereUnique_id_Input',
    '_FamilyMemberWhereUnique_linkedUserId_Input',
]


class FamilyMemberUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    name: _str
    relation: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    user: 'UserUpdateOneWithoutRelationsInput'
    linkedUser: 'UserUpdateOneWithoutRelationsInput'


class FamilyMemberUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    name: _str
    relation: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class FamilyMemberUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['FamilyMemberCreateWithoutRelationsInput']
    connect: List['FamilyMemberWhereUniqueInput']
    connect_or_create: List['FamilyMemberConnectOrCreateWithoutRelationsInput']
    set: List['FamilyMemberWhereUniqueInput']
    disconnect: List['FamilyMemberWhereUniqueInput']
    delete: List['FamilyMemberWhereUniqueInput']

    # TODO
    # update: List['FamilyMemberUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['FamilyMemberUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['FamilyMemberScalarWhereInput']
    # upsert: List['FamilyMemberUpserteWithWhereUniqueWithoutRelationsInput']


class FamilyMemberUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'FamilyMemberCreateWithoutRelationsInput'
    connect: 'FamilyMemberWhereUniqueInput'
    connect_or_create: 'FamilyMemberConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'FamilyMemberUpdateInput'
    # upsert: 'FamilyMemberUpsertWithoutRelationsInput'


class FamilyMemberUpsertInput(TypedDict):
    create: 'FamilyMemberCreateInput'
    update: 'FamilyMemberUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_FamilyMember_id_OrderByInput = TypedDict(
    '_FamilyMember_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_FamilyMember_userId_OrderByInput = TypedDict(
    '_FamilyMember_userId_OrderByInput',
    {
        'userId': 'SortOrder',
    },
    total=True
)

_FamilyMember_name_OrderByInput = TypedDict(
    '_FamilyMember_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_FamilyMember_relation_OrderByInput = TypedDict(
    '_FamilyMember_relation_OrderByInput',
    {
        'relation': 'SortOrder',
    },
    total=True
)

_FamilyMember_linkedUserId_OrderByInput = TypedDict(
    '_FamilyMember_linkedUserId_OrderByInput',
    {
        'linkedUserId': 'SortOrder',
    },
    total=True
)

_FamilyMember_createdAt_OrderByInput = TypedDict(
    '_FamilyMember_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_FamilyMember_updatedAt_OrderByInput = TypedDict(
    '_FamilyMember_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

_FamilyMember_RelevanceInner = TypedDict(
    '_FamilyMember_RelevanceInner',
    {
        'fields': 'List[FamilyMemberScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_FamilyMember_RelevanceOrderByInput = TypedDict(
    '_FamilyMember_RelevanceOrderByInput',
    {
        '_relevance': '_FamilyMember_RelevanceInner',
    },
    total=True
)

FamilyMemberOrderByInput = Union[
    '_FamilyMember_id_OrderByInput',
    '_FamilyMember_userId_OrderByInput',
    '_FamilyMember_name_OrderByInput',
    '_FamilyMember_relation_OrderByInput',
    '_FamilyMember_linkedUserId_OrderByInput',
    '_FamilyMember_createdAt_OrderByInput',
    '_FamilyMember_updatedAt_OrderByInput',
    '_FamilyMember_RelevanceOrderByInput',
]



# recursive FamilyMember types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

FamilyMemberRelationFilter = TypedDict(
    'FamilyMemberRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class FamilyMemberListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class FamilyMemberInclude(TypedDict, total=False):
    """FamilyMember relational arguments"""
    user: Union[bool, 'UserArgsFromFamilyMember']
    linkedUser: Union[bool, 'UserArgsFromFamilyMember']


    

class UserIncludeFromFamilyMember(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive1']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive1']


class UserIncludeFromFamilyMemberRecursive1(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive2']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive2']


class UserIncludeFromFamilyMemberRecursive2(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive3']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive3']


class UserIncludeFromFamilyMemberRecursive3(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    familyMembers: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive4']
    linkedAsMember: Union[bool, 'FindManyFamilyMemberArgsFromFamilyMemberRecursive4']


class UserIncludeFromFamilyMemberRecursive4(TypedDict, total=False):
    """Relational arguments for FamilyMember"""

    

class UserArgsFromFamilyMember(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromFamilyMemberRecursive1(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromFamilyMemberRecursive2(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromFamilyMemberRecursive3(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromFamilyMemberRecursive4(TypedDict, total=False):
    """Arguments for FamilyMember"""
    
    

class FindManyUserArgsFromFamilyMember(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromFamilyMemberRecursive1(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromFamilyMemberRecursive2(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromFamilyMemberRecursive3(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromFamilyMemberRecursive4(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class FamilyMemberIncludeFromFamilyMember(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    user: Union[bool, 'UserArgsFromFamilyMemberRecursive1']
    linkedUser: Union[bool, 'UserArgsFromFamilyMemberRecursive1']


class FamilyMemberIncludeFromFamilyMemberRecursive1(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    user: Union[bool, 'UserArgsFromFamilyMemberRecursive2']
    linkedUser: Union[bool, 'UserArgsFromFamilyMemberRecursive2']


class FamilyMemberIncludeFromFamilyMemberRecursive2(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    user: Union[bool, 'UserArgsFromFamilyMemberRecursive3']
    linkedUser: Union[bool, 'UserArgsFromFamilyMemberRecursive3']


class FamilyMemberIncludeFromFamilyMemberRecursive3(TypedDict, total=False):
    """Relational arguments for FamilyMember"""
    user: Union[bool, 'UserArgsFromFamilyMemberRecursive4']
    linkedUser: Union[bool, 'UserArgsFromFamilyMemberRecursive4']


class FamilyMemberIncludeFromFamilyMemberRecursive4(TypedDict, total=False):
    """Relational arguments for FamilyMember"""

    

class FamilyMemberArgsFromFamilyMember(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive1'


class FamilyMemberArgsFromFamilyMemberRecursive1(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive2'


class FamilyMemberArgsFromFamilyMemberRecursive2(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive3'


class FamilyMemberArgsFromFamilyMemberRecursive3(TypedDict, total=False):
    """Arguments for FamilyMember"""
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive4'


class FamilyMemberArgsFromFamilyMemberRecursive4(TypedDict, total=False):
    """Arguments for FamilyMember"""
    
    

class FindManyFamilyMemberArgsFromFamilyMember(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive1'


class FindManyFamilyMemberArgsFromFamilyMemberRecursive1(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive2'


class FindManyFamilyMemberArgsFromFamilyMemberRecursive2(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive3'


class FindManyFamilyMemberArgsFromFamilyMemberRecursive3(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    include: 'FamilyMemberIncludeFromFamilyMemberRecursive4'


class FindManyFamilyMemberArgsFromFamilyMemberRecursive4(TypedDict, total=False):
    """Arguments for FamilyMember"""
    take: int
    skip: int
    order_by: Union['FamilyMemberOrderByInput', List['FamilyMemberOrderByInput']]
    where: 'FamilyMemberWhereInput'
    cursor: 'FamilyMemberWhereUniqueInput'
    distinct: List['FamilyMemberScalarFieldKeys']
    


FindManyFamilyMemberArgs = FindManyFamilyMemberArgsFromFamilyMember
FindFirstFamilyMemberArgs = FindManyFamilyMemberArgsFromFamilyMember


    

class FamilyMemberWhereInput(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    userId: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    relation: Union[_str, 'types.StringFilter']
    linkedUserId: Union[None, _int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    user: 'UserRelationFilter'
    linkedUser: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['FamilyMemberWhereInputRecursive1', List['FamilyMemberWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['FamilyMemberWhereInputRecursive1']
    OR: List['FamilyMemberWhereInputRecursive1']
    NOT: List['FamilyMemberWhereInputRecursive1']


class FamilyMemberWhereInputRecursive1(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    userId: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    relation: Union[_str, 'types.StringFilter']
    linkedUserId: Union[None, _int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    user: 'UserRelationFilter'
    linkedUser: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['FamilyMemberWhereInputRecursive2', List['FamilyMemberWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['FamilyMemberWhereInputRecursive2']
    OR: List['FamilyMemberWhereInputRecursive2']
    NOT: List['FamilyMemberWhereInputRecursive2']


class FamilyMemberWhereInputRecursive2(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    userId: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    relation: Union[_str, 'types.StringFilter']
    linkedUserId: Union[None, _int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    user: 'UserRelationFilter'
    linkedUser: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['FamilyMemberWhereInputRecursive3', List['FamilyMemberWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['FamilyMemberWhereInputRecursive3']
    OR: List['FamilyMemberWhereInputRecursive3']
    NOT: List['FamilyMemberWhereInputRecursive3']


class FamilyMemberWhereInputRecursive3(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    userId: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    relation: Union[_str, 'types.StringFilter']
    linkedUserId: Union[None, _int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    user: 'UserRelationFilter'
    linkedUser: 'UserRelationFilter'

    # should be noted that AND and NOT should be Union['FamilyMemberWhereInputRecursive4', List['FamilyMemberWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['FamilyMemberWhereInputRecursive4']
    OR: List['FamilyMemberWhereInputRecursive4']
    NOT: List['FamilyMemberWhereInputRecursive4']


class FamilyMemberWhereInputRecursive4(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    userId: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    relation: Union[_str, 'types.StringFilter']
    linkedUserId: Union[None, _int, 'types.IntFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    user: 'UserRelationFilter'
    linkedUser: 'UserRelationFilter'



# aggregate FamilyMember types


    

class FamilyMemberScalarWhereWithAggregatesInput(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    userId: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    relation: Union[_str, 'types.StringWithAggregatesFilter']
    linkedUserId: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['FamilyMemberScalarWhereWithAggregatesInputRecursive1']
    OR: List['FamilyMemberScalarWhereWithAggregatesInputRecursive1']
    NOT: List['FamilyMemberScalarWhereWithAggregatesInputRecursive1']


class FamilyMemberScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    userId: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    relation: Union[_str, 'types.StringWithAggregatesFilter']
    linkedUserId: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['FamilyMemberScalarWhereWithAggregatesInputRecursive2']
    OR: List['FamilyMemberScalarWhereWithAggregatesInputRecursive2']
    NOT: List['FamilyMemberScalarWhereWithAggregatesInputRecursive2']


class FamilyMemberScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    userId: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    relation: Union[_str, 'types.StringWithAggregatesFilter']
    linkedUserId: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['FamilyMemberScalarWhereWithAggregatesInputRecursive3']
    OR: List['FamilyMemberScalarWhereWithAggregatesInputRecursive3']
    NOT: List['FamilyMemberScalarWhereWithAggregatesInputRecursive3']


class FamilyMemberScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    userId: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    relation: Union[_str, 'types.StringWithAggregatesFilter']
    linkedUserId: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['FamilyMemberScalarWhereWithAggregatesInputRecursive4']
    OR: List['FamilyMemberScalarWhereWithAggregatesInputRecursive4']
    NOT: List['FamilyMemberScalarWhereWithAggregatesInputRecursive4']


class FamilyMemberScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """FamilyMember arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    userId: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    relation: Union[_str, 'types.StringWithAggregatesFilter']
    linkedUserId: Union[_int, 'types.IntWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']



class FamilyMemberGroupByOutput(TypedDict, total=False):
    id: _int
    userId: _int
    name: _str
    relation: _str
    linkedUserId: _int
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    _sum: 'FamilyMemberSumAggregateOutput'
    _avg: 'FamilyMemberAvgAggregateOutput'
    _min: 'FamilyMemberMinAggregateOutput'
    _max: 'FamilyMemberMaxAggregateOutput'
    _count: 'FamilyMemberCountAggregateOutput'


class FamilyMemberAvgAggregateOutput(TypedDict, total=False):
    """FamilyMember output for aggregating averages"""
    id: float
    userId: float
    linkedUserId: float


class FamilyMemberSumAggregateOutput(TypedDict, total=False):
    """FamilyMember output for aggregating sums"""
    id: _int
    userId: _int
    linkedUserId: _int


class FamilyMemberScalarAggregateOutput(TypedDict, total=False):
    """FamilyMember output including scalar fields"""
    id: _int
    userId: _int
    name: _str
    relation: _str
    linkedUserId: _int
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


FamilyMemberMinAggregateOutput = FamilyMemberScalarAggregateOutput
FamilyMemberMaxAggregateOutput = FamilyMemberScalarAggregateOutput


class FamilyMemberMaxAggregateInput(TypedDict, total=False):
    """FamilyMember input for aggregating by max"""
    id: bool
    userId: bool
    name: bool
    relation: bool
    linkedUserId: bool
    createdAt: bool
    updatedAt: bool


class FamilyMemberMinAggregateInput(TypedDict, total=False):
    """FamilyMember input for aggregating by min"""
    id: bool
    userId: bool
    name: bool
    relation: bool
    linkedUserId: bool
    createdAt: bool
    updatedAt: bool


class FamilyMemberNumberAggregateInput(TypedDict, total=False):
    """FamilyMember input for aggregating numbers"""
    id: bool
    userId: bool
    linkedUserId: bool


FamilyMemberAvgAggregateInput = FamilyMemberNumberAggregateInput
FamilyMemberSumAggregateInput = FamilyMemberNumberAggregateInput


FamilyMemberCountAggregateInput = TypedDict(
    'FamilyMemberCountAggregateInput',
    {
        'id': bool,
        'userId': bool,
        'name': bool,
        'relation': bool,
        'linkedUserId': bool,
        'createdAt': bool,
        'updatedAt': bool,
        '_all': bool,
    },
    total=False,
)

FamilyMemberCountAggregateOutput = TypedDict(
    'FamilyMemberCountAggregateOutput',
    {
        'id': int,
        'userId': int,
        'name': int,
        'relation': int,
        'linkedUserId': int,
        'createdAt': int,
        'updatedAt': int,
        '_all': int,
    },
    total=False,
)


FamilyMemberKeys = Literal[
    'id',
    'userId',
    'name',
    'relation',
    'linkedUserId',
    'createdAt',
    'updatedAt',
    'user',
    'linkedUser',
]
FamilyMemberScalarFieldKeys = Literal[
    'id',
    'userId',
    'name',
    'relation',
    'linkedUserId',
    'createdAt',
    'updatedAt',
]
FamilyMemberScalarFieldKeysT = TypeVar('FamilyMemberScalarFieldKeysT', bound=FamilyMemberScalarFieldKeys)

FamilyMemberRelationalFieldKeys = Literal[
        'user',
        'linkedUser',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields